# Default values for britbus-data-importer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

database:
  connectionStringSecret: britbus-mongodb-admin-britbus
  database: britbus

image:
  repository: ghcr.io/britbus/britbus/data-importer
  pullPolicy: Always
  tag: main

tasks:
  - name: travelinenoc
    schedule: "0 2 * * 0"
    args: ["file", "traveline-noc", "https://www.travelinedata.org.uk/noc/api/1.0/nocrecords.xml"]
  - name: naptan
    schedule: "0 3 * * 6"
    args: ["file", "naptan", "https://naptan.api.dft.gov.uk/v1/access-nodes?dataFormat=xml"]
  - name: bods-timetable
    schedule: "0 5 * * 6"
    args: ["bods-timetable", "--url", "https://data.bus-data.dft.gov.uk/api/v1/dataset/?limit=25&offset=0&status=published&api_key=NOPE"]

resources: {}
podAnnotations: {}
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""